### ISSUE TITLE
Tamaños de fuentes

### ISSUE THREAD

**Issue by saimon2989** [DupuyAle/Dupuy-MercadoLiebre#1]
Hola Ale, creo que tu codigo en la parte del header, especificamente en el navbar puede mejorar para que se vea mas acercado al ejercicio y mas amigable en cuanto a UX UI.

Lo que hice fue: cambiarle el tamaño de fuente al siguiente codigo css 
`header ul li a{
    text-decoration: none;
    color: #000;
    display: inline;
    font-size: 16px;
}` 

a  16px, el tamaño recomendado para pantallas desktop es entre 14 y 18px o pt. o entre 1rem y 1.125rem.

Resultado Obtenido:

<img width="1045" alt="Captura de Pantalla 2023-09-05 a la(s) 12 32 07 p m" src="https://github.com/DupuyAle/Dupuy-MercadoLiebre/assets/73040737/eed7f7e5-0816-42f5-a2e4-541b0df92563">

La navbar Al ser un elemento tan importante siempre tiene que destacar y ser relevante para la vista del usuario ya que es indispensable para la interaccion de los usuarios en los sitios web. 
En este caso aumentamos el tamaño de la fuente y Se ve mas legible, contrasta mas con el fondo amarrillo y toma mas relevancia en el layout del sitio web.

Espero te sirva, igual es una opinion y forma de hacerlo personal, quiza hayan mejores formas e incluso mejores practicas.
Saludos,

**Comment by DupuyAle** [comment]
dale gracias por la correccion del codigo.
